---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iotdb.apache.org
  resources:
  - datanodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iotdb.apache.org
  resources:
  - datanodes/finalizers
  verbs:
  - update
- apiGroups:
  - iotdb.apache.org
  resources:
  - datanodes/status
  verbs:
  - get
  - patch
  - update
