---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-iotdb-apache-org-v1-confignode
  failurePolicy: Fail
  name: mconfignode.kb.io
  rules:
  - apiGroups:
    - iotdb.apache.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - confignodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-iotdb-apache-org-v1-datanode
  failurePolicy: Fail
  name: mdatanode.kb.io
  rules:
  - apiGroups:
    - iotdb.apache.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - datanodes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-iotdb-apache-org-v1-confignode
  failurePolicy: Fail
  name: vconfignode.kb.io
  rules:
  - apiGroups:
    - iotdb.apache.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - confignodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-iotdb-apache-org-v1-datanode
  failurePolicy: Fail
  name: vdatanode.kb.io
  rules:
  - apiGroups:
    - iotdb.apache.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - datanodes
  sideEffects: None
