apiVersion: v1
kind: PersistentVolume
metadata:
  name: confignode-storage1
  labels:
    app: confignode-storage
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s_iotdb/data/confignode1
    type: DirectoryOrCreate