apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-storage1
  labels:
    app: datanode-storage
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s_iotdb/data/datanode1
    type: DirectoryOrCreate